name: App Test

on:
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: unbuntu-latest

        env:
            MODE: "dev"

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r ./requirements.txt
            
            - name: Test App Code
              run: python ./code_test.py