name: App Test

on:
    pull_request:
        branches:
            - main
jobs:
    # Run test
    test:
        runs-on: ubuntu-latest

        env:
            # Initialized in environment
            SECRET_KEY: ${{ secrets.SECRET_KEY }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r ./requirements.txt
            
            - name: Print SECRET_KEY
              run: echo $SECRET_KEY

            - name: Test App Code
              run: python ./code_test.py